[versions]

compile-sdk = "35"
min-sdk = "23"
target-sdk = "35"
jvm = "17"

androidGradlePlugin = "8.7.3"

koinCore = "4.1.0"
koinAndroid = "4.1.0"
koinAndroidxCompose = "4.1.0"

kotlin = "2.1.0"
kotlinGradlePlugin = "1.9.0"
kotlinxCoroutines = "1.10.2"

ksp = "2.1.0-1.0.29"

compose = "1.8.3"
composeMaterial = "1.3.2"
composeNavigation = "2.9.3"
composeConstraint = "1.1.1"
composeActivity = "1.10.1"

androidxDataStore = "1.1.7"
androidxCore = "1.16.0"
androidxCamera = "1.4.2"
androidMaterial = "1.12.0"

lifecycle = "2.9.2"

# Room
room = "2.7.2"

googleMlkitDetection = "17.0.2"
googleMlkitScanning = "17.3.0"

junit4 = "4.13.2"
androidJUnit = "1.3.0"
testEspresso = "3.7.0"
uiTooling = "1.8.3"

[libraries]
androidx-dataStore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
androidx-camera = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCamera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCamera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidxCamera" }

lifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }

google-mlkit-detection = { group = "com.google.mlkit", name = "object-detection", version.ref = "googleMlkitDetection" }
google-mlkit-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "googleMlkitScanning" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koinCore" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinAndroidxCompose" }

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

# Compose
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-uiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-material = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
compose-constraint = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraint" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Testing
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidJUnit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "testEspresso" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }